-
  name: EC2 Intance Provisioning
  hosts: local
  connection: local
  tasks:
  -
    name: Create Security Group
    local_action: 
       module: ec2_group
       name: "{{ security_group }}"
       region: "{{region}}"
       description: "{{ec2_group_description}}"
       rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
#       register: basic_firewall
  -
     name: Instance Launch
     local_action: ec2
                      group="{{ security_group }}"
                      instance_type="{{ instance_type}}"
                      image="{{ image }}"
                      wait=true
                      region="{{ region }}"
                      keypair="{{ keypair }}"
                      count="{{count}}"
     register: ec2
  -
     name: Wait for SSH to come up
     local_action: wait_for
        host="{{ item.public_ip }}"
        port=22
        state=started
     with_items: "{{ ec2.instances }}"

#  - name: Add tag to Instance(s)
#        local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
#        with_items: ec2.instances
#        args:
#          tags:
#            Name: Server-1
